name: scuba_sweep
description: A new Flutter project.

publish_to: 'none' 

version: 1.2.1+24

environment:
  sdk: '>3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  easy_localization: ^3.0.7+1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  freezed_annotation: ^3.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  package_info_plus: ^8.3.0
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  flutter_easyloading: ^3.0.5
  crypto: ^3.0.6
  flutter_local_notifications: ^19.0.0
  flutter_local_notifications_linux: ^6.0.0
  firebase_messaging: ^15.2.4
  firebase_dynamic_links: ^6.1.4
  dio: ^5.8.0+1
  flame: ^1.26.0
  uuid: ^4.5.1
  cloud_firestore: ^5.6.5
  json_annotation: ^4.9.0
  dart_openai: ^5.1.0
  flutter_svg: ^2.0.17
  add_to_google_wallet: ^0.0.5
  envied: ^1.1.1
  flame_audio: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  envied_generator: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/launcher_icons/
    - assets/images/
    - assets/audio/

  fonts:
     - family: LilitaOne
       fonts:
         - asset: assets/fonts/LilitaOne-Regular.ttf